build-fedora:
  image: fedora:latest
  stage: test
  before_script:
    - dnf install -y redhat-rpm-config meson git gcc gstreamer1-devel gstreamer1-plugins-base-devel gdk-pixbuf2-devel totem-pl-parser-devel
  script:
    - git submodule update --init
    - meson _build
    - ninja -C _build install
